### PR TITLE
Upgrade Babel 7

### PR DESCRIPTION
**Pull request by pioug**
https://github.com/schmod/babel-plugin-angularjs-annotate/issues/42

- Update `package.json` using `npx babel-upgrade`
- Generate package lock with npm@6.0.1
- Update unit tests. 
  - Set `compact: true` when calling `babel.transform` to have consistent whitespace
  - Change quotes in "expected" code: It seems like Babel 7 generates code using double quote.
> If you want formatting for compiled output you can use recast/prettier/escodegen/fork babel-generator. - http://new.babeljs.io/docs/en/next/v7-migration.html

~~The current `babelify` still depends on `babel@6` though~~

### CODE REVIEW

**Comment by vitaliusvs** [comment]
Are there any maintainers?

**Comment by schmod** [comment]
Sorry, I've fallen behind on keeping this up to date.  I'll try to take a look at open PRs this week!

**Comment by pioug** [comment]
Hello @schmod! Thank you for reviewing the PR 👍 I saw you bumped the package version but the package has not been published on npm yet. Is there anything blocking the release? Maybe I can help if needed.

**Comment by schmod** [comment]
No, that's totally my fault.  I could have sworn I published it.  _facepalm_

**Comment by schmod** [comment]
published 0.10.0

**Pull request merged**
